name: Build and push SGX container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login -u ${git -p ${GITHUB_TOKEN}
      - uses: actions/checkout@v1
      - name: submodule update
        run: git submodule update --init --recursive
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag  skalenetwork/sgxwallet:latest
      - name: push docker image
        run:  docker push skalenetwork/sgxwallet:latest
